<?php if(Router::getController()!='administrador'){ ?>

<!-- Beginning of compulsory code below -->

<ul class="dropdown dropdown-horizontal">

<?php 
$menu = new Menu();
$s_menu = new Menu();

foreach($menu->find("posicion_x<>0","order: orden") as $menu):

echo "<li>";
	echo "<a href='".core::getInstancePath()."$menu->url' class='dir' title='$menu->tittle'>$menu->descripcion</a>";
			
			if($s_menu->count("posicion_y='$menu->posicion_x'")){			
				echo "<ul>";

					foreach($s_menu->find("posicion_y='$menu->posicion_x'","order: orden") as $s_menu):
					
					echo "<li>";
						echo "<a href='".core::getInstancePath()."$s_menu->url' class='dir' title='$s_menu->tittle'>$s_menu->descripcion</a>";
					echo "</li>";
					
					endforeach;
				
				echo "</ul>";
			}
		
		
echo "</li>";

endforeach;
?>

	<!--<li><a href="./" class="dir" title="">Download Drivers</a>

		<ul>

			<li><a href="./">Download Drivers</a></li>

			<li><a href="./">Driver Widget</a></li>

			<li><a href="./">NVIDIA Software</a></li>

		</ul>

	</li>

	<li><a href="./" class="dir">Shop</a>
    	<ul>
        	<li><a href="./" class="dir">Shop</a>
            	<ul><li><a href="./" class="dir">Shop</a></li></ul>
            </li>
        </ul>
    </li>

	<li><a href="./" class="dir">Products</a>

		<ul>

			<li><a href="./">Desktop</a></li>

			<li><a href="./">Workstation</a></li>

			<li><a href="./">Servers</a></li>

			<li><a href="./">Motherboard</a></li>

			<li><a href="./">High Performance Computing</a></li>

			<li><a href="./">Notebook</a></li>

			<li><a href="./">Mobile</a></li>

			<li><a href="./">Business</a></li>

			<li><a href="./">Apple</a></li>

			<li><a href="./">Software</a></li>

			<li><a href="./">Home Entertainment</a></li>

			<li><a href="./">Downloadable Games</a></li>

			<li><a href="./">Game Console</a></li>

			<li><a href="./">Legacy Products</a></li>

			<li><a href="./">Promotions</a></li>

			<li><a href="./">Where to Buy</a></li>

		</ul>

	</li>

	<li><a href="./" class="dir">Technologies</a>

		<ul>

			<li><a href="./">NVIDIA SLI</a></li>

			<li><a href="./">NVIDIA Hybrid SLI</a></li>

			<li><a href="./">ESA</a></li>

			<li><a href="./">NVIDIA PureVideo</a></li>

			<li><a href="./">CUDA</a></li>

			<li><a href="./">NVIDIA PhysX</a></li>

			<li><a href="./">MXM</a></li>

			<li><a href="./">Windows Vista</a></li>

		</ul>

	</li>

	<li><a href="./" class="dir">Communities</a>

		<ul>

			<li><a href="./">nZone</a></li>

			<li><a href="./">SLI Zone</a></li>

			<li><a href="./">CUDA Zone</a></li>

			<li><a href="./">Developer Zone</a></li>

			<li><a href="./">PartnerForce</a></li>

			<li><a href="./">Gelato Zone</a></li>

		</ul>

	</li>

	<li><a href="./" class="dir">Company Info</a>

		<ul>

			<li><a href="./">Investor Relations</a></li>

			<li><a href="./">Channel Partners</a></li>

			<li><a href="./">Contact Information</a></li>

			<li><a href="./">Corporate Milestones</a></li>

			<li><a href="./">Social Responsibility</a></li>

			<li><a href="./">Employment</a></li>

			<li><a href="./">University Relations</a></li>

			<li><a href="./">Executive Profiles</a></li>

			<li><a href="./">Corporate Awards</a></li>

		</ul>

	</li>

	<li><a href="./" class="dir">News</a>

		<ul>

			<li><a href="./">Press Room</a></li>

			<li><a href="./">NVISION</a></li>

			<li><a href="./">Events Calendar</a></li>

			<li><a href="./">Success Stories</a></li>

			<li><a href="./">NVIDIA in the News</a></li>

			<li><a href="./">NVIDIA Newsletter</a></li>

		</ul>

	</li>

	<li><a href="./" class="dir">Support</a></li>

</ul>-->

<?php } ?>

<!-- / END -->


