<table id="tablaturnos"></table>
<div id="pagerturnos"></div>
<script>
jQuery(document).ready(function(){

		
		jQuery("#tablaturnos").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath(); ?>turnos/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Id','Empleado ID','Nombre Empleado','Fecha Inicio','Fecha Fin'], 
			colModel:[ 
				{ name:'id',index:'id', width:20}, 
				{ name:'empleado_id',index:'empleado_id', width:20},
				{ name:'nombre_empleado',index:'nombre_empleado', width:20},
				{ name:'inicio',index:'inicio' },
				{ name:'fin',index:'fin' }
			], 
			autoWidth:true,
			width: 550,
			height: 250,
			rowNum:10, 
			rowList:[10,20,30,40,50], 
			pager: '#pagerturnos', 
			sortname: 'tipo_auto', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"listado de Tipos de Autos",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					jQuery("#tipo_auto_id").val(fila['id']);
					jQuery("#nombre_tipo_auto").val(fila['tipo_auto']);
					jQuery("#dialogo_tipo_auto").dialog("close");
       		 }
		}); 
		jQuery("#tablaturnos").jqGrid('navGrid','#pagerturnos',{edit:false,add:false,del:false}); 
		jQuery("#tablaturnos").jqGrid('navButtonAdd','#pagerturnos',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#tablaturnos").jqGrid('columnChooser');
		}
	});
});
</script>