<?php 
	if(isset($_REQUEST["opcion"])){
		Flash::notice("Doble Click en la Fila para ".$_REQUEST["opcion"]); 
	}
?>
<table id="tabla<?php echo Router::getController(); ?>"></table>
<div id="pager<?php echo Router::getController(); ?>"></div>
<script>
jQuery(document).ready(function(){

		
		jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Id','Texto Pregunta','Fecha Creación','Usuarios ID'], 
			colModel:[ 
				{ name:'id'		       ,index:'id'			     },
				{ name:'texto_pregunta'   ,index:'texto_pregunta'     },
				{ name:'fecha_creacion'   ,index:'fecha_creacion'     }, 
				{ name:'usuarios_id'      ,index:'fecha_cierre'       }
				],				
				autoWidth:true,
				width: 550,
				height: 250,
				rowNum:50, 
				/*rowList:[10,20,30,40,50], */
				pager: '#pager<?php echo Router::getController(); ?>', 
				sortname: 'id', 
				/*shrinkToFit :false,*/
				viewrecords: true, 
				sortorder: "asc", 
				caption:"LISTADO DE PREGUNTAS",
				ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					if( jQuery("#preguntas_id")    ){ jQuery("#preguntas_id").val(fila['id']); }
					if( jQuery("#texto_pregunta") ){ jQuery("#texto_pregunta").val(fila['texto_pregunta']); } 
					if( jQuery("#fecha_creacion") ){ jQuery("#fecha_creacion").val(fila['fecha_creacion']); } 
					if( jQuery("#usuarios_id") ){ jQuery("#usuarios_id").val(fila['usuarios_id']); } 
					
					
					<?php if(isset($_REQUEST["opcion"]) ){ ?>
					redireccionar_action("<?php echo Router::getController(); ?>/<?php echo $_REQUEST["opcion"]; ?>/"+fila['id'] );
					<?php }else{?>	
						jQuery("#dialogo_<?php echo Router::getController(); ?>").dialog("close");
					<?php } ?>
					
       		 }
		});
		 
		/*jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navGrid','#pager<?php //echo Router::getController(); ?>',{edit:false,add:false,del:false}); 
		jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navButtonAdd','#pager<?php //echo Router::getController(); ?>',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('columnChooser');
		
	});}*/
});
</script>