<div align="center">
  <table border="0" cellpadding="2" id="remisiones"  cellspacing="2">
    <tr>
      <td align="center"><?php echo Tag::linkTo("#", Tag::image("64x64/Back.png",'width: 32px'),"onClick: window.close();") ?></td>
      <td align="center"><?php echo Tag::linkTo("menu/", Tag::image("iconos/inicio.png",'width: 32px'),"tittle: Regresar al Menu"); ?></td>
    </tr>
    <tr>
      <td align="center">Regresar</td>
      <td align="center">Inicio</td>
    </tr>
  </table>
</div>
<?php echo View::getContent(); ?>