<form id="traslados" name="traslados">
<h4><?php echo $tipo_documento; echo " - "; echo $tipo_documento_nombre;  ?></h4>
<table width="100%" border="0" align="center" cellpadding="2" cellspacing="4">
  <tr>
    <td width="18%" align="right"><div align="right">EMPRESA</div></td>
    <td colspan="4">
        <?php echo Tag::hiddenField("id"); ?> 
		<?php echo Tag::hiddenField("tipo_documento_id"); ?> 
        <?php echo Tag::hiddenField("empresa_id"); ?> 
        <?php echo Tag::hiddenField("prefijo2"); ?> 
        <?php echo Tag::hiddenField("consecutivo"); ?> 
		<?php echo Tag::textField("nombre_empresa","size: 30","readOnly: readOnly","style: background: #cccccc;"); ?>
        </td>
  </tr>
  
  <tr>
   <tr>
    <td align="right"><div align="right">BODEGAS DESDE</div></td>
    <td width="39%" align="left" valign="middle" id="aclientes">
		<?php echo Tag::textField("desde_bodegas_id","size: 4","readOnly: readOnly","style: background: #cccccc;"); ?>
		<?php echo Tag::textField("nombre_desde_bodegas","size: 50","readOnly: readOnly","style: background: #cccccc;"); ?>
    <td colspan="3" align="left" valign="middle" id="aclientes">    
    <button id="buscar_desde_bodegas" type="button">Buscar</button>
    <!--<button id="agregar_bodegas" type="button">Agregar Proveedor</button> -->
  </tr>
  <tr>
   <tr>
    <td align="right"><div align="right">BODEGAS HASTA</div></td>
    <td width="39%" align="left" valign="middle" id="aclientes">
		<?php echo Tag::textField("hasta_bodegas_id","size: 4","readOnly: readOnly","style: background: #cccccc;"); ?>
		<?php echo Tag::textField("nombre_hasta_bodegas","size: 50","readOnly: readOnly","style: background: #cccccc;"); ?>
    <td colspan="3" align="left" valign="middle" id="aclientes">    
    <button id="buscar_hasta_bodegas" type="button">Buscar</button>
    <!--<button id="agregar_bodegas" type="button">Agregar Proveedor</button> -->
  </tr>
  <tr>
    <td align="right" valign="top">FECHA</td>
    <td><div align="left">
      <input type="text" size="10" id="fecha" name="fecha"  />
      <span class="ui-icon ui-icon-calendar" style="float:left;"></span> </div></td>
    <td width="10%">HORA</td>
    <td width="18%" align="right" valign="top"><div align="left">
        <input type="text" size="10" id="hora" name="hora"  />
        <span class="ui-icon ui-icon-calendar" style="float:left;"></span> </div></td>
    <td width="15%">&nbsp;</td>
  </tr>
  <tr>
    <td align="right" valign="top">OBSERVACIONES</td>
    <td colspan="4"><input type="text"  id="observaciones" name="observaciones" size="50" maxlength="50"/></td>
    </tr>
</table>
<table id="grid_traslados"></table>
<div id="pagtraslados"></div>
  
  <button id="agregar_item" type="button">Agregar</button>
  <button id="buscar_item" type="button">Buscar</button>
  <button id="modificar_item" type="button">Modificar</button>
<button id="borrar_item" type="button">Borrar</button>
 <br />

<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" id="f3">
  <tr>
    <td width="50%">&nbsp;</td>
    <th align="right">CANTIDAD TOTAL </th>
    <td><?php echo Tag::textField("total","size: 12"); ?></td>
  </tr>
</table>

	<div align="center">
    	<button id="guardar" type="button">Guardar</button>
        <button id="cancelar" type="button">Cancelar</button>
    </div>

<p>&nbsp;</p>

<div id="mensajes"></div>

</form>

<div title="Agergar Producto a la Compra" id="dialogo_agregar_item">
	
    <table width="70%" cellpadding="2" cellspacing="2" align="center">
        <tr>
   	       <td>Referencia</td>
            <td><input type="text" readonly="readonly" size="2" id="tmp_kardex_id" name="tmp_kardex_id" /></td>
            <input type="hidden"  id="tmp_codigo" name="tmp_codigo" />
            <td><input type="text"  id="tmp_referencia" name="tmp_referencia"/></td>
        </tr>
        <tr>
       	    <td>Cantidad(Und)</td>
            <td colspan="2"><input type="text"  id="tmp_cantidad" value="1" name="tmp_cantidad"/></td>
        </tr>
       
    </table>

</div>


<div title="Modificar Producto de la Compra" id="dialogo_modificar_item">
	
    <table width="70%" cellpadding="2" cellspacing="2" align="center">
       <tr>
   	      <td>Id</td>
           <td colspan="2"><input type="text"  id="tmp_id_mod" name="tmp_id_mod" value="0" size="2" /></td>
        </tr>
        <tr>
   	      <td>Kardex ID</td>
           <td colspan="2"><input type="text"  id="tmp_kardex_id_mod" name="tmp_kardex_id_mod" value="0" size="2" /></td>
        </tr>
     	<tr>
   	      <td>REFERENCIA</td>
           <td colspan="2"><input type="hidden"  id="tmp_codigo_mod" name="tmp_codigo_mod" /><input type="text"  id="tmp_referencia_mod" name="tmp_referencia_mod"/></td>
        </tr>
        <tr>
       	    <td>Cantidad(Und)</td>
            <td colspan="2">
            <!--<input type="hidden" readonly="readonly" size="2" id="tmp_id_mod" name="tmp_id_mod" />
            <input type="hidden" readonly="readonly" size="2" id="tmp_kardex_id_mod" name="tmp_kardex_id_mod" />-->
            <input type="text"  id="tmp_cantidad_mod" value="1" name="tmp_cantidad_mod"/></td>
        </tr>
       
    </table>

</div>



<?php 

$ents  = new Traslados();
$emp = new Empresa();
$bg  = new Bodegas();
$dt  = new DetalleTraslados();
$kd  = new Kardex();

$id                         = '';
$tipo_documento_id          = $tipo_documento;
$empresa_id                 = Session::get("id_empresa");
$nombre_empresa             = Session::get("nombre_empresa");
$fecha                      = date("Y-m-d H:m:s");
$hora                       = date("H:m:s");
$nombre_proveedores         = '';
$desde_bodegas_id           = '1';
$nombre_desde_bodegas       = $bg->findFirst("id = '$desde_bodegas_id '")->bodega;
$hasta_bodegas_id           = '';
$nombre_hasta_bodegas       = '';
$prefijo2                   = '';
$consecutivo                = '';
$observaciones              = '';
$anulado                    = '';

	if(isset($_REQUEST["id"])){ 
	
		
		if($_REQUEST["id"]!=''){
			
			//if($ents->count("conditions: id = '".$_REQUEST["id"]."' and anulado = 0 ")>0){
			
				$id = $_REQUEST["id"];
				$encabezado = $ents->findFirst(" id = '".$_REQUEST["id"]."' and anulado = 0 ");
				//Flash::notice(print_r($encabezado));
				$id                         = $encabezado->id;
				$tipo_documento_id          = $encabezado->tipo_documento_id;
				$empresa_id                 = $encabezado->empresa_id;
				$nombre_empresa             = $emp->findFirst("id = '$empresa_id'")->nombre_empresa;
				$fecha                      = $encabezado->fecha;
				$hora                       = $encabezado->hora;
				$desde_bodegas_id           = $encabezado->desde_bodegas_id;
				$nombre_desde_bodegas       = $bg->findFirst("id = '$desde_bodegas_id '")->bodega;
				$hasta_bodegas_id           = $encabezado->hasta_bodegas_id;
				$nombre_hasta_bodegas       = $bg->findFirst("id = '$hasta_bodegas_id '")->bodega;
				$prefijo2                   = $encabezado->prefijo;
				$consecutivo                = $encabezado->consecutivo;
				$anulado                    = $encabezado->anulado;
				$observaciones              = $encabezado->observaciones;
			
		//}
	
	
	 }
	
	}
?>


<script type="text/javascript">



jQuery(document).ready(function(){


var detalles = [];

<?php
if(isset($_REQUEST["id"])){ 
		if($_REQUEST["id"]!=''){ 
				//if($pd->count("conditions: anulado = 0 and id = '".$_REQUEST["id"]."' ") == 0){ ?>
						jQuery("#id").val("<?php echo $id; ?>");	
						jQuery("#tipo_documento_id").val("<?php echo $tipo_documento_id; ?>");	
						jQuery("#empresa_id").val("<?php echo $empresa_id; ?>");	
						jQuery("#nombre_empresa").val("<?php echo $nombre_empresa; ?>");	
						jQuery("#fecha").val("<?php echo $fecha; ?>");	
						jQuery("#hora").val("<?php echo $hora; ?>");	
						jQuery("#desde_bodegas_id").val("<?php echo $desde_bodegas_id; ?>");	
						jQuery("#nombre_desde_bodegas").val("<?php echo $nombre_desde_bodegas; ?>");	
						jQuery("#hasta_bodegas_id").val("<?php echo $hasta_bodegas_id; ?>");	
						jQuery("#nombre_hasta_bodegas").val("<?php echo $nombre_hasta_bodegas; ?>");	
						jQuery("#prefijo2").val("<?php echo $prefijo2; ?>");	
						jQuery("#consecutivo").val("<?php echo $consecutivo; ?>");	
						jQuery("#observaciones").val("<?php echo $observaciones; ?>");	
						
						<?php foreach($dt->find(" traslados_id = '$id' ") as $dt): ?>
								detalles.push(
										{
											 id:         "<?php echo $dt->id; ?>"     
											,kardex_id:  "<?php echo $dt->kardex_id; ?>" 
											,referencia: "<?php echo $kd->findFirst(" id = '$dt->kardex_id' ")->codigo; ?>"
											,nombre:     "<?php echo $kd->findFirst(" id = '$dt->kardex_id' ")->nombre_producto; ?>" 
											,cantidad:   "<?php echo $dt->cantidad; ?>" 
											,costo:      "<?php echo $dt->costo; ?>" 
											,total:      "<?php echo $dt->total; ?>" 
											,anulado:    "<?php if($dt->anulado==0){ echo "NO"; }else{ echo "SI"; } ?>" 
										}
									);
						<?php endforeach; ?>
						reload_grid();
						
   <?php 		//}
   
 	  }
}else{ ?>
						jQuery("#tipo_documento_id").val("<?php echo $tipo_documento_id; ?>");	
						jQuery("#empresa_id").val("<?php echo $empresa_id; ?>");	
						jQuery("#nombre_empresa").val("<?php echo $nombre_empresa; ?>");	
						jQuery("#fecha").val("<?php echo $fecha; ?>");	
						jQuery("#hora").val("<?php echo $hora; ?>");	
						jQuery("#desde_bodegas_id").val("<?php echo $desde_bodegas_id; ?>");
						jQuery("#nombre_desde_bodegas").val("<?php echo $nombre_desde_bodegas; ?>");	
<?php
}		
?>



/*--------------------------------------------Guardar traslados Especiales--------------------------------------------------------------*/


jQuery("#guardar").click(function(){
		guardar_compra();
});


function guardar_compra(){
	var datos = "";
	var srv = JSON.stringify(detalles);
	//datos = jQuery("#compras").serialize();
	jQuery( "#progressbar" ).progressbar({ value: 50 });	
		//$('#resumen').html('Cargando....');
		var jqXHR = jQuery.ajax({
			type: "POST",
			url: "<?php echo core::getInstancePath(); ?>traslados/add",
			data: {
					id:                jQuery("#id").val(),
					proveedores_id:    jQuery("#proveedores_id").val(),
					prefijo:           jQuery("#prefijo2").val(),
					consecutivo:       jQuery("#consecutivo").val(),
					tipo_documento_id: jQuery("#tipo_documento_id").val(),
					empresa_id:        jQuery("#empresa_id").val(),
					desde_bodegas_id:  jQuery("#desde_bodegas_id").val(),
					hasta_bodegas_id:  jQuery("#hasta_bodegas_id").val(),
					fecha:             jQuery("#fecha").val(),
					hora:              jQuery("#hora").val(),
					observaciones:     jQuery("#observaciones").val(),
					detalles: srv
			},
			success: function(data) {
				jQuery( '#mensajes' ).html("");
				jQuery( "#progressbar" ).progressbar({ value: 90 });
				jQuery( '#mensajes' ).html(data);
			},
			error: function(data) {
				jQuery('#dialogo_mensajes').html("Error Enviando parametros.....");
				jQuery( "#progressbar" ).progressbar({ value: 0 });
				jQuery('#dialogo_mensajes').dialog("open");
			}
		});
		
		 jqXHR.done(function(data){
			jQuery( "#progressbar" ).progressbar({ value: 0 });
		});
}


/*--------------------------------------------------Agregar item---------------------------------------------------------------------------------*/



function agregar_item(data){

	
var existe = false;   
/*for(i=0;i<detalles.length;i++) {  
	if (detalles[i]["id"] == data["id"]) {  
	   alert("Articulo ya esta en la entrada especial");  
	   existe = true;  
	 }   
 }  
if (!existe) {  */
	detalles.push(
		{
			 id:data["id"]
			,kardex_id:data["kardex_id"]
			,referencia:data["referencia"]
			,nombre:data["nombre"]
			,cantidad:data["cantidad"]
			,costo:data["costo"]
			,total:data["total"]
			,anulado: "NO"
		}
	);
	reload_grid();
/*}  */

}


 jQuery("#agregar_item").click(function(){
	
	if( jQuery("#bodegas_id").val() != '' ){
		jQuery("#dialogo_agregar_item").dialog("open");
		//reload_grid();
	}else{
		jQuery("#dialogo_mensajes").html("");
		jQuery("#dialogo_mensajes").html("Por Favor escoja una Bodega");
		jQuery("#dialogo_mensajes").dialog("open");
	}

});
	 
	 
//autocomplete con json	
jQuery( "#tmp_referencia" ).autocomplete({
	source: "<?php echo core::getInstancePath(); ?>kardex/autocompletejson",
	minLength: 2,
	select: function( event, ui ) {
		 //alert("Has seleccionado: " + ui.item.value);
		 jQuery("#tmp_referencia").val(ui.item.value)
		 jQuery("#tmp_kardex_id").val(ui.item.id);
		 jQuery("#tmp_codigo").val(ui.item.codigo);
	}
});
	


jQuery("#dialogo_agregar_item").dialog(
{ 
	autoOpen:false
	, width:600 
	, heigth:400 
	,modal: true
	,buttons:[
		{
			text:  "Escoger"
			,click: function(){
					var datos;
					
					datos += "&tmp_referencia=" + jQuery("#tmp_referencia").val();
					datos += "&tmp_cantidad="   + jQuery("#tmp_cantidad").val();
					datos += "&tmp_descuento="  + jQuery("#tmp_descuento").val();
					datos += "&tmp_costo="      + jQuery("#tmp_costo").val();
					
					var jqXHR = jQuery.ajax({
							url:"<?php echo core::getInstancePath(); ?>traslados/agregar_item/",
							type:"POST",
							dataType:"json",
							data:{
									bodegas_id:     jQuery("#bodegas_id").val(),
									fecha:          jQuery("#fecha").val(),
									tmp_kardex_id:  jQuery("#tmp_kardex_id").val(),
									tmp_codigo:     jQuery("#tmp_codigo").val(),
									tmp_referencia: jQuery("#tmp_referencia").val(),
									tmp_cantidad:   jQuery("#tmp_cantidad").val(),
									tmp_descuento:  jQuery("#tmp_descuento").val(),
									tmp_costo:      jQuery("#tmp_costo").val()
								}
								,
								fail:function(){
									alert("error");
								},
								error:function(jqXHR,textStatus,errorThrown){
									alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
								}
					});
					
					 jqXHR.done(function(data){
						agregar_item(data);
					});
					
					jQuery(this).dialog("close"); 
					
				}	
		}
	]
});

function reload_grid(){
	jQuery("#grid_traslados").jqGrid('setGridParam',
		{ 	datatype: 'local',
			data:detalles
		}).trigger("reloadGrid");
}

/*-----------------------------------------------------modificar item----------------------------------------------------------------------------*/
//agregar un item al vector json de items
function modificar_item(data,mod_id){
	for(i=0;i<detalles.length;i++){
			if(detalles[i].id==mod_id){
				detalles[i].id          = data["id"];
				detalles[i].kardex_id   = data["kardex_id"];
				detalles[i].referencia  = data["referencia"];
				detalles[i].nombre      = data["nombre"];
				detalles[i].cantidad    = data["cantidad"];
				detalles[i].costo       = data["costo"];
				detalles[i].total       = data["total"];
				detalles[i].anulado     = data["anulado"];
			}
	}
	reload_grid();

}

//cuadro de dialogo de agregar item...	 
jQuery("#modificar_item").click(function(){
		
		toMod = jQuery("#grid_traslados").jqGrid('getGridParam','selrow');
		var sw = 0;
		
		for(i=0;i<detalles.length;i++){
			if(detalles[i].id==toMod){
				//alert("Lo Encontre: "+detalles[i].id + " SUBSTRING TEMP " + detalles[i].id.substring(0,4));
				if( detalles[i].anulado == "SI" ){
					alert("Elemento Anulado no se Puede Modificar");
					sw=1;
				}else{
					//alert("liena guardada en la base de datos anular");
					jQuery("#tmp_id_mod").val(detalles[i].id);
					jQuery("#tmp_kardex_id_mod").val(detalles[i].kardex_id);
					jQuery("#tmp_codigo_mod").val(detalles[i].referencia);
					jQuery("#tmp_referencia_mod").val(detalles[i].nombre);
					jQuery("#tmp_cantidad_mod").val(detalles[i].cantidad);
					var costo = parseFloat(detalles[i].costo);
					jQuery("#tmp_costo_mod").val(costo);
					sw=0;
						
					}
			}
		}
		
		if(sw==0){
			jQuery("#dialogo_modificar_item").dialog("open");
		}
	//reload_grid();
});

	
jQuery("#dialogo_modificar_item").dialog(
{ 
	autoOpen:false
	, width:600 
	, heigth:400 
	,modal: true
	,buttons:[
		{
			text:  "Escoger"
			,click: function(){
					var mod_id =         jQuery("#tmp_id_mod").val();
					//alert(mod_id);
					var jqXHR = jQuery.ajax({
							url:"<?php echo core::getInstancePath(); ?>traslados/agregar_item/",
							type:"POST",
							dataType:"json",
							data:{
									inlcuye_iva:    jQuery("#incluye_iva").val(),
									tmp_id:         jQuery("#tmp_id_mod").val(),
									tmp_kardex_id:  jQuery("#tmp_kardex_id_mod").val(),
									tmp_referencia:  jQuery("#tmp_referencia_mod").val(),
									tmp_codigo:     jQuery("#tmp_codigo_mod").val(),
									tmp_cantidad:   jQuery("#tmp_cantidad_mod").val(),
									tmp_descuento:  jQuery("#tmp_descuento_mod").val(),
									tmp_costo:      jQuery("#tmp_costo_mod").val(),
									tmp_bodega_id:   jQuery("#bodegas_id").val(),
									fecha:          jQuery("#fecha").val()
								}
								,
								fail:function(){
									alert("error");
								},
								error:function(jqXHR,textStatus,errorThrown){
									alert("error "+textStatus+"\n"+jqXHR+"\n"+errorThrown);
								}
					});
					
					 jqXHR.done(function(data){
						modificar_item(data,mod_id);
					});
					
					jQuery(this).dialog("close"); 
					
				}	
		}
	]
});



/*-------------------------------------------------------delete item----------------------------------------------------*/

var grid = jQuery("#grid_traslados"),
	delSettings = {
		afterShowForm: function (jQueryform) {
			// delete button: "#dData", cancel button: "#eData"
			jQuery("#dData", jQueryform.parent()).click();
		},
		// because I use "local" data I don't want to send the changes to the server
		// so I use "processing:true" setting and delete the row manually in onclickSubmit
		onclickSubmit: function (options) {
			var gridId = grid[0].id,
				gridP = grid[0].p,
				newPage = gridP.page,
				rowids = gridP.multiselect ? gridP.selarrrow : [gridP.selrow];

			// reset the value of processing option to true
			// because the value can be changed by jqGrid
			options.processing = true;

			// delete the row
			jQuery.each(rowids, function () {
				grid.jqGrid('delRowData', this);
				
			});
			jQuery.jgrid.hideModal("#delmod" + gridId,
								{ gb: "#gbox_" + gridId,
									jqm: options.jqModal,
									onClose: options.onClose });

			if (gridP.lastpage > 1) {// on the multipage grid reload the grid
				if (gridP.reccount === 0 && newPage === gridP.lastpage) {
					// if after deliting there are no rows on the current page
					// which is the last page of the grid
					newPage -= 1; // go to the previous page
				}
				// reload grid to make the row from the next page visable.
				grid.trigger("reloadGrid", [{ page: newPage}]);
			}

			return true;
		},
		processing: true
	};


//cuadro de dialogo de agregar item...	 
jQuery("#borrar_item").click(function(){
//jQuery("#dialogo_agregar_item").dialog("open");
if(confirm("Realmente Desea Borrar o Anular el Registro")){
	//var gr = jQuery("#grid_entradas").jqGrid('getGridParam','selrow');
	//jQuery("#grid_entradas").find("#"+gr).remove();
	toDelete = jQuery("#grid_traslados").jqGrid('getGridParam','selrow');
	var sw = 0;
	
	for(i=0;i<detalles.length;i++){
		if(detalles[i].id==toDelete){
			//alert("Lo Encontre: "+detalles[i].id + " SUBSTRING TEMP " + detalles[i].id.substring(0,4));
			if( detalles[i].id.substring(0,4) == 'temp' ){
				//alert("linea temporarl borrar");
				sw=0;
			}else{
				//alert("liena guardada en la base de datos anular");
				sw=1;
				detalles[i].anulado = "SI";
					
				}
		}
	}

	//alert(detalles["id"][toDelete]);
	//jQuery("#grid_entradas").jqGrid('delGridRow',toDelete,myDelOptions);
	if(sw==0){
		
		if( toDelete != null ) {
			if(jQuery("#grid_traslados").delGridRow(toDelete,delSettings)){
				detalles = jQuery.grep(
							detalles, 
							function (item,index) { 
							  return item.id !=  toDelete; 
							});

			}else{
					alert("no borro nada");
				}
			//getSelectedRow();
		}else{ alert("Por favor seleccione una fila para borrar!"); }
	}else{
			//alert("anular");
			reload_grid();
		}
	//reload_grid();
}
});

/*------------------------------------------------ Configurar Grilla de Entradas especiales --------------------------------------------------------------------*/


/*grib maestros de clientes*/
function config_gridCompras(){
		grid_fndCompras = jQuery("#grid_traslados").jqGrid({
			datatype:"local",
			data: detalles,
			height:200,
			rowNum:25,
			autowidth:true,
			pager:"#pagtraslados",
			
			colNames:['Id','Kardex Id','Referencia','Nombre','Cantidad','Costo','Total',"Anulado"],
			colModel:[
			{   name:'id',          index:'id',          sorttype:'text'                        },
			{	name:'kardex_id',	index:'kardex_id',	 sorttype:'text'	                    },
			{	name:'referencia',	index:'referencia',	 sorttype:'text'	                    },
			{	name:'nombre',		index:'nombre',		 sorttype:'text',   width: 300          },
			{	name:'cantidad',    index:'cantidad',    sorttype:'integer', formatter:"number" },
			{	name:'costo',		index:'costo',       sorttype:'double',	 formatter:"number" },
			{	name:'total',		index:'total',    	 sorttype:'double',	 formatter:"number" },
			{	name:'anulado',		index:'anulado',  	 sorttype:'text',    width: 50          }
			],
			multiselect:false,
			caption:"Detalle Traslados",
			sortname: 'id', 
			viewrecords: true, 
			sortorder: "desc",
		
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				
			}
		});
	}

config_gridCompras();


});
</script>


