<table id="mytable">
<thead>
   <tr>
    <th>NIT</th>
    <th>RAZON SOCIAL</th>
    <th>VER</th>
    <th>MODIFICAR</th>
  </tr>
</thead>  
<tbody>
        <?php 
		 $i=0;	
		 foreach($detalles as $det): ?>  
          <tr>
            <td><?php echo $det->nit;?></td>
            <td><?php echo $det->razon_social;?></td>
            <td><div align="center"><?php echo Tag::linkTo("proveedores/show/$det->id", Tag::image("iconos/buscar.png","width: 20"),"target: _blank") ?></div></td>
            <td><div align="center"><?php echo Tag::linkTo("proveedores/modificar/$det->id", Tag::image("iconos/editar.png","width: 20"),"target: _blank") ?></div></td>

          </tr>
        <?php $i++; endforeach; ?> 
 <tbody>       
 </table>
 <script>
	jQuery(document).ready(function(e) {
		  
		   config = tableToGrid("#mytable",{
					
					height: 'auto', 
					/*autowidth:true,*/
					viewrecords: true,
					loadui: true,
					 /*pager : "#ptreegrid2",*/
					caption: "LISTADO DE PROVEEDORES SEGUN SU CRITERIO DE BUSQUEDA" 
	   });
	  }); 
 </script>  