
<br />
<table width="50%"  align="center" cellpadding="2" cellspacing="2">
 <tr>
    <th colspan="6" class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix" align="left">
   		 Buscar Alertas de Clientes    </th>
</tr>
 
   <tr>
     <td align="right">Placa</td>
     <td align="left"><?php echo Tag::textField("placa", "size: 15") ?></td>
     <td align="left">&nbsp;</td>
   </tr>
   <tr>
    <td align="right">Fecha Inicio</td>
    <td align="left"><?php echo Tag::textField("fecha_inicio", "size: 15") ?></td>
    <td align="left">&nbsp;</td>
  </tr>
  
  <tr>
    <td align="right">Fecha Fin</td>
    <td align="left"><?php echo Tag::textField("fecha_fin", "size: 15") ?></td>
    <td align="left">&nbsp;</td>
  </tr>
</table>
<br />
<div align="center">
	<button id="enviar">Enviar</button>
</div>

<br /><br />

<div id="mensajes">

</div>


<script>

jQuery(function() {

jQuery("#progressbar").attr('style','display:none;');
jQuery("#progressbarWrapper").attr('style','display:none;');

jQuery("#enviar").click(function(){
	enviar();
});

function enviar(){
var datos = "";
jQuery( '#mensajes' ).html("");
jQuery( "#progressbar" ).progressbar({ value: 50 });	
	var jqXHR = jQuery.ajax({
		type: "POST",
		url: "<?php echo core::getInstancePath(); ?>alertas/detalle_buscar",
		data: {
				id:             jQuery("#id").val(),
				fecha_inicio:   jQuery("#fecha_inicio").val(),
				fecha_fin:      jQuery("#fecha_fin").val(),
				empleado_id:    jQuery("#empleado_id").val(),
				anulado:        jQuery("#anulado").val(),
				
		},
		success: function(data) {
			jQuery( '#mensajes' ).html("");
			jQuery( "#progressbar" ).progressbar({ value: 90 });
			jQuery( '#mensajes' ).html(data);
		},
		error: function(data) {
			jQuery('#dialogo_mensajes').html("Error Enviando parametros.....");
			jQuery( "#progressbar" ).progressbar({ value: 0 });
			jQuery('#dialogo_mensajes').dialog("open");
		}
	});

 	jqXHR.done(function(data){
		jQuery( "#progressbar" ).progressbar({ value: 0 });
	});

}



jQuery( "#placa" ).autocomplete({
	source: "<?php echo core::getInstancePath(); ?>pedido_clientes/placaautocomplete",
	minLength: 1,
	select: function( event, ui ) {
		 //alert("Has seleccionado: " + ui.item.value);
		 jQuery("#placa").val(ui.item.value)
		 /*jQuery("#color").val(ui.item.color);*/
		 /*jQuery("#tipo_auto_id").val(ui.item.tipo_auto_id);
		 jQuery("#clase_vehiculo_id").val(ui.item.clase_vehiculo_id);
		 jQuery("#nombre_tipo_auto").val(ui.item.tipo_auto);
		 jQuery("#nombre_clase_vehiculo").val(ui.item.clase_vehiculo);
		 
		 jQuery("#buscar_clase_vehiculo").attr("disabled","disabled");
		 jQuery("#buscar_tipo_auto").attr("disabled","disabled");*/
		 
	}
});

});


</script>

