<?php //echo View::getContent(); ?>
<?php
	//foreach(View::getValidationMessages() as $message){
		//Flash::error($message->getMessage());
	//}
	
//print_r(Extensions::getLoadedExtensions());	
?>


<div id="caja" class="caja">
    <?php echo Tag::form('administrador/valida') ?>
    <table width="600px" align="center" title="Inicio de Sesion"> 
      <thead >
        <tr>
            <th colspan="6" class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix" align="left">
            <?php echo Tag::image("iconos/clientes.png", "width: 32", "height: 32", "border: 0", "alt: Sadascol Ltda"); ?> INICIO DE SESSION            </th>
        </tr>
	</thead>
  <tbody>
    <tr>
        <td width="25%" rowspan="5" valign="middle" align="left"> 
	    <?php echo Tag::image("inicio_session.png", "border: 0","width: 100"); ?>          </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
        <tr>
          <td width="32%" align="right"><div align="right">Nombre de Usuario:</div></td>
          <td width="43%"><?php echo Tag::textField('login','size: 20') ?></td>		
        </tr>
        <tr>
          <td align="right"><div align="right">Password:</div></td>

          <td align="left"><?php echo Tag::passwordField('password','size: 20') ?></td>
        </tr>
        <tr>
          <td><div align="right">Empresa</div></td>
          <td><?php $empresa = new Empresa(); echo Tag::select("empresa",$empresa->find(),'using: id,nombre_corto'); ?></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
            <th colspan="3"><button type="submit" id="inicio" name="inicio">Iniciar Sesion</button></th>
        </tr>
         <tr>
            <th colspan="3">
           			<?php echo View::getContent(); ?>
					<?php
                        foreach(View::getValidationMessages() as $message){
                            Flash::error($message->getMessage());
                        }
                    ?>            </th>
        </tr>
        </tbody>
    </table>
</div>   
<?php echo Tag::endForm(); ?>
<!--
<script>

jQuery(document).ready(function(){

     jQuery(window).resize(function(){
 
          // aquí le pasamos la clase o id de nuestro div a centrar (en este caso "caja")
          jQuery('.caja').css({
               position:'absolute',
               left: (jQuery(window).width() - jQuery('.caja').outerWidth())/2,
               top: (jQuery(window).height() - jQuery('.caja').outerHeight())/2
          });
       
    });

// Ejecutamos la función
jQuery(window).resize();

jQuery("#progressbar").attr('style','display:none;');
jQuery("#progressbarWrapper").attr('style','display:none;');
 
}); 

</script> -->