<?php echo Tag::formRemote("inventario/listar_inventario", "update: mensajes", "id: inventario","name: inventario"); ?>
<table width="100%" border="0" cellpadding="0" id="r1">
  <tr>
    <th colspan="6">LISTADO DE INVENTARIO</th>
  </tr>
  <tr>
    <td><div align="right">Grupo:</div></td>
    <td><?php echo Tag::checkboxField("g","value:g","checked:checked"); ?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td width="19%">&nbsp;</td>
    <td width="10%"><div id="div_lista"></div></td>
    <td width="20%"><?php echo Tag::submitButton("Enviar"); ?></td>
    <td width="26%">&nbsp;</td>
    <td width="26%">&nbsp;</td>
	<td width="26%">&nbsp;</td>
  </tr>
</table>
<div id="mensajes"></div>

<?php echo Tag::endForm(); ?>

<script type="text/javascript">
  
  jQuery(document).ready(function(){
   jQuery("#g").change(function(evento){
    //elimino el comportamiento por defecto del enlace
  	 evento.preventDefault();
      //Aquí pondría el código de la llamada a Ajax
	 	url = 	"<?php echo core::getInstancePath(); ?>inventario/traer_grupos/"; 
		jQuery("#div_lista").load(url);
			  
     });
   
   });


</script>
